const CONFIG = {
  WEB_APP_URL: "https://script.google.com/macros/s/AKfycbwd6KRJo7YHEaEkhKvKfkEnj6AUq8CnvcAUhKnOMPhz_Sw89nKve4YkCrrz5yzhICkYrw/exec",
  API_KEY: "ZGM3YjJhMzEtNWU0Yi00YjZjLWE5MzctZjIxNGU4YzRhOTEx",
  WORKING_INSTRUCTIONS_URL: "https://grades-db.vercel.app/",

  GRADES_DB_SHEET_URL: "https://docs.google.com/spreadsheets/d/15iK49B5J77MIuuNCMSOjOr9uilsKuSJvF8wuPenoaD8",
  GRADES_DB_SHEET_LABEL: "Grades DB",
  CHARACTER_DB_SHEET_URL: "https://docs.google.com/spreadsheets/d/1nOP8uUGG7JpitYRmsJwpbQwygiDR92c9mMMMdZyGO08",
  CHARACTER_DB_SHEET_LABEL: "Character DB",
  ATTENDANCE_DB_SHEET_URL: "https://docs.google.com/spreadsheets/d/1fn-bIIHCoieXLA3pnM9ExzueWi9qu7zYNNUblBo7Cvw",
  ATTENDANCE_DB_SHEET_LABEL: "Attendance DB",

  // Template Masterfile spreadsheets, one per grade band. Used to validate that an
  // imported OGS file was actually generated by the official Template Masterfile (its
  // spreadsheet ID must appear in that masterfile's MASTER_DATA!Column E).
  TEMPLATE_MASTERFILE_URLS: {
    "1-3": "https://docs.google.com/spreadsheets/d/1AF4xhpB1JeC7VTrIPKEzS7ZkPV6xyHgJPA_4Wdag3AE",
    "4-6": "https://docs.google.com/spreadsheets/d/1U7nzecx28sa86ida_LmwMIISf4OGyuTxAtiPreVh7gQ",
    "7-10": "https://docs.google.com/spreadsheets/d/1osyW21crqazBl8vqdL0TGYaz2gvZ114qtcjTsImyRo4",
    "11-12": "https://docs.google.com/spreadsheets/d/1KxUs6RxMZduLMwpMoDB5qb6hcO1PyJlSWATavM-h-jM"
  },

  TRANSMUTATION_REF: 'TRANSMUTATION_REF',

  TERMS: {
    FIRST: '1ST',
    SECOND: '2ND',
    THIRD: '3RD'
  }
};

